server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://localhost:3306/lxfdb
    username: root
    password: Mysql80@deb
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP配置
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    database: ${REDIS_DATABASE:0}

pebble:
  # 前缀设为空, 或空字符串"", 都可以！
  suffix:
  cache: false
